### ISSUE TITLE
No Module name trades_simul

### ISSUE THREAD

**Issue by onthetunnel** [Reidmcc/Binance-bot#2]
Hello i got this issue hope you can help me solve it Thanks You !

**Comment by Reidmcc** [comment]
That's a legacy module name, it should have been replaced by mult_arbit. I've fixed it in data_checks.py. Thanks for the catch.

**Comment by onthetunnel** [comment]
Thanks for solving this problem ! and can i know how to trade using btc , and minimum amount for trade,  and the target profit % Thanks You!

**Comment by Reidmcc** [comment]
Binance's rules for trade amounts are here: https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule. Neither strategy sets an explicit profit target.
