### ISSUE TITLE
There appear to be some issue with the API system used here

### ISSUE THREAD

**Issue by UnitTHK** [Reidmcc/Binance-bot#3]
I’ll leave the code trace back here:
`thk@ubuntu2004vncheroku-s-1vcpu-1gb-sgp1-01:~/binance-test$ python3 run_mult_arbit.py 
 <traceback object at 0x7faef1b3c480> Open order request failed try again
 <traceback object at 0x7faef1700b80> Open order request failed try again
 <traceback object at 0x7faef1700a40> Open order request failed try again
 <traceback object at 0x7faef184be80> Open order request failed try again
 <traceback object at 0x7faef25f9280> Open order request failed try again
 <traceback object at 0x7faef1708c80> Open order request failed try again
^CTraceback (most recent call last):
  File "/home/thk/binance-test/mult_arbit.py", line 1082, in get_open_ords
    open_ords = client.openOrders(pair)
  File "/home/thk/binance-test/api.py", line 315, in openOrders
    return self._get('v3/openOrders?', p)
  File "/home/thk/binance-test/api.py", line 84, in _get
    return self._request(endpoint, param, "get")
  File "/home/thk/binance-test/api.py", line 78, in _request
    raise MalformedRequest(r.text)
excepts.MalformedRequest

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_mult_arbit.py", line 31, in <module>
    a = tr.get_open_ords('XLMBNB')
  File "/home/thk/binance-test/mult_arbit.py", line 1088, in get_open_ords
    time.sleep(1)
KeyboardInterrupt
`

I removed some of the client.get_offset() function, because they always cause error when I run them, maybe the API changed?

**Comment by szxyks** [comment]
@ducanh2002123 Were you able to get the Binance-bot working? If yes, which strategies you used, cross-pair arbitrage or breakout trend trading?

**Comment by UnitTHK** [comment]
@sd0minick I ended up just writing another script because fixing this took way longer than just writing a new one

**Comment by szxyks** [comment]
@ducanh2002123 would you mind passing me over your script, I'd appreciate it.
